using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ServerEditVsro
{
    public partial class Avatar : Form
    {
        public Avatar()
        {
            InitializeComponent();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void radioButton21_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (radioButton1.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ANGEL_WING_DRESS 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ANGEL_WING_DRESS 0"; }
            if (radioButton2.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ARABIA 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ARABIA_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ARABIA_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ARABIA 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ARABIA_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ARABIA_ATTACH 0"; }
            if (radioButton3.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CH_WEDDING 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CH_WEDDING_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CH_WEDDING 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CH_WEDDING_HAT 0"; }
            if (radioButton4.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DARKLKNIGHT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DARKLKNIGHT_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DARKLKNIGHT_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DARKLKNIGHT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DARKLKNIGHT_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DARKLKNIGHT_ATTACH 0"; }
            if (radioButton5.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM /MAKEITEM ITEM_MALL_AVATAR_M_FUR 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_FUR_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_FUR 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_FUR_HAT 0"; }
            if (radioButton6.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NEWHALLOWEEN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NEWHALLOWEEN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NEWHALLOWEEN_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NEWHALLOWEEN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NEWHALLOWEEN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NEWHALLOWEEN_ATTACH 0"; }
            if (radioButton7.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SHOGUN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SHOGUN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SHOGUN_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NINJA 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NINJA_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NINJA_ATTACH 0"; }
            if (radioButton8.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DEVIL_WING_DRESS 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DEVIL_WING_DRESS 0"; }
            if (radioButton9.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_BLACKWING 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_BLACKWING_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_BLACKWING 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_BLACKWING_HAT 0"; }
            if (radioButton10.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_EU_WEDDING 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_EU_WEDDING_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CH_WEDDING 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CH_WEDDING_HAT 0"; }
            if (radioButton11.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_EARTHSPIRIT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_EARTHSPIRIT_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_EARTHSPIRIT_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_EARTHSPIRIT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_EARTHSPIRIT_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_EARTHSPIRIT_ATTACH 0"; }
            if (radioButton12.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_HALLOWEEN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_HALLOWEEN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_HALLOWEEN_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_HALLOWEEN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_HALLOWEEN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_HALLOWEEN_ATTACH 0"; }
            if (radioButton13.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_PIRATE 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_PIRATE_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_PIRATE_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_PIRATE 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_PIRATE_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_PIRATE_ATTACH 0"; }
            if (radioButton14.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_TURKEY 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_TURKEY_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_TURKEY 0\r\n/ITEM_MALL_AVATAR_W_TURKEY_HAT 0"; }
            if (radioButton15.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NASRUN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NASRUN_BLUE 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NASRUN_UNIQUE 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NASRUN_YELLOW 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NASRUN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NASRUN_BLUE 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NASRUN_UNIQUE 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NASRUN_YELLOW 0\r\n--Amalrun Male--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_AMALRUN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_AMALRUN_YELLOW 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_AMALRUN_BLUE 0\r\n--Amalrun Female--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_AMALRUN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_AMALRUN_YELLOW 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_AMALRUN_BLUE 0"; }
            if (radioButton16.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CRANIVAL 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CRANIVAL_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CRANIVAL_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CRANIVAL 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CRANIVAL_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CRANIVAL_ATTACH 0"; }
            if (radioButton17.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CLOWN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CLOWN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_CLOWN_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CLOWN 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CLOWN_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_CLOWN_ATTACH 0"; }
            if (radioButton18.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_MALL_WINTER 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_MALL_WINTER_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_MALL_WINTER_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_MALL_WINTER 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_MALL_WINTER_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_MALL_WINTER_ATTACH 0"; }
            if (radioButton19.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_KNIGHT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_KNIGHT_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_KNIGHT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_KNIGHT_HAT 0"; }
            if (radioButton20.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_PIRATECREW 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_PIRATECREW_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_PIRATECRER_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_PIRATECREW 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_PIRATECREW_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_PIRATECREW_ATTACH 0"; }
            if (radioButton21.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SPARTA 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SPARTA_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SPARTA_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_SPARTA 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_SPARTA_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_SPARTA_ATTACH 0"; }
            if (radioButton22.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_FAIRY 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_FAIRY_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_FAIRY 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_FAIRY_HAT 0"; }
            if (radioButton23.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NEWDEVIL 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_NEWDEVIL_HAT 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NEWDEVIL 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_NEWDEVIL_HAT 0"; }
            if (radioButton24.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SAINTWARRIOR 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SAINTWARRIOR_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_SAINTWARRIOR_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_SAINTWARRIOR 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_SAINTWARRIOR_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_SAINTWARRIOR_ATTACH 0"; }
            if (radioButton25.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ADMIRAL 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ADMIRAL_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ADMIRAL_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ADMIRAL 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ADMIRAL_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ADMIRAL_ATTACH 0"; }
            if (radioButton26.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ARABIA_2013 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ARABIA_2013_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_ARABIA_2013_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ARABIA_2013 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ARABIA_2013_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_ARABIA_2013_ATTACH 0"; }
            if (radioButton27.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_MUMMY 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_MUMMY_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_MUMMY_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_MUMMY 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_MUMMY_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_MUMMY_ATTACH 0"; }
            if (radioButton28.Checked == true) { textBox1.Text = "--MALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DARKWARRIOR 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DARKWARRIOR_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_M_DARKWARRIOR_ATTACH 0\r\n--FEMALE--\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DARKWARRIOR 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DARKWARRIOR_HAT 0\r\n/MAKEITEM ITEM_MALL_AVATAR_W_DARKWARRIOR_ATTACH 0"; }
        }

        private void Avatar_Load(object sender, EventArgs e)
        {
            if (Language.Default.language == "English")
            {
                button1.Text = "Show Code";
                button2.Text = "Back";
            }
        }
    }
}