using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ServerEditVsro
{
    public partial class LegendaryArmor : Form
    {
        public LegendaryArmor()
        {
            InitializeComponent();
        }

        private void radioButton1_CheckedChanged(object sender, EventArgs e)
        {
            listBox1.Hide();
            listBox5.Show();
        }

        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {
            listBox5.Hide();
            listBox1.Show();

        }

        private void button2_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void listBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_CLOTHES.Show(); } else { DEGREE_11_SET_A_M_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_LIGHT.Show(); } else { DEGREE_11_SET_A_M_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_HEAVY.Show(); } else { DEGREE_11_SET_A_M_HEAVY.Visible = false; }
            if (listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_CLOTHES.Show(); } else { DEGREE_11_SET_A_W_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_LIGHT.Show(); } else { DEGREE_11_SET_A_W_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_HEAVY.Show(); } else { DEGREE_11_SET_A_W_HEAVY.Visible = false; }
            if (listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_CLOTHES.Show(); } else { DEGREE_11_SET_B_M_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_LIGHT.Show(); } else { DEGREE_11_SET_B_M_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_HEAVY.Show(); } else { DEGREE_11_SET_B_M_HEAVY.Visible = false; }
            if (listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_CLOTHES.Show(); } else { DEGREE_11_SET_B_W_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_LIGHT.Show(); } else { DEGREE_11_SET_B_W_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_HEAVY.Show(); } else { DEGREE_11_SET_B_W_HEAVY.Visible = false; }
        }
        private void listBox5_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_CLOTHES.Show(); } else { DEGREE_11_SET_A_M_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_LIGHT.Show(); } else { DEGREE_11_SET_A_M_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_HEAVY.Show(); } else { DEGREE_11_SET_A_M_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_CLOTHES.Show(); } else { DEGREE_11_SET_A_W_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_LIGHT.Show(); } else { DEGREE_11_SET_A_W_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_HEAVY.Show(); } else { DEGREE_11_SET_A_W_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_CLOTHES.Show(); } else { DEGREE_11_SET_B_M_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_LIGHT.Show(); } else { DEGREE_11_SET_B_M_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_HEAVY.Show(); } else { DEGREE_11_SET_B_M_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_CLOTHES.Show(); } else { DEGREE_11_SET_B_W_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_LIGHT.Show(); } else { DEGREE_11_SET_B_W_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_HEAVY.Show(); } else { DEGREE_11_SET_B_W_HEAVY.Visible = false; }
        }
        private void listBox2_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (listBox1.SelectedIndex == 0) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_CLOTHES.Show(); } else { DEGREE_11_SET_A_M_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 1) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_LIGHT.Show(); } else { DEGREE_11_SET_A_M_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 2) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_HEAVY.Show(); } else { DEGREE_11_SET_A_M_HEAVY.Visible = false; }
            if (listBox1.SelectedIndex == 3) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_CLOTHES.Show(); } else { DEGREE_11_SET_A_W_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 4) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_LIGHT.Show(); } else { DEGREE_11_SET_A_W_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 5) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_HEAVY.Show(); } else { DEGREE_11_SET_A_W_HEAVY.Visible = false; }
            if (listBox1.SelectedIndex == 0) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_CLOTHES.Show(); } else { DEGREE_11_SET_B_M_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 1) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_LIGHT.Show(); } else { DEGREE_11_SET_B_M_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 2) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_HEAVY.Show(); } else { DEGREE_11_SET_B_M_HEAVY.Visible = false; }
            if (listBox1.SelectedIndex == 3) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_CLOTHES.Show(); } else { DEGREE_11_SET_B_W_CLOTHES.Visible = false; }
            if (listBox1.SelectedIndex == 4) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_LIGHT.Show(); } else { DEGREE_11_SET_B_W_LIGHT.Visible = false; }
            if (listBox1.SelectedIndex == 5) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_HEAVY.Show(); } else { DEGREE_11_SET_B_W_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 0) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_CLOTHES.Show(); } else { DEGREE_11_SET_A_M_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 1) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_LIGHT.Show(); } else { DEGREE_11_SET_A_M_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 2) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_M_HEAVY.Show(); } else { DEGREE_11_SET_A_M_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 3) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_CLOTHES.Show(); } else { DEGREE_11_SET_A_W_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 4) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_LIGHT.Show(); } else { DEGREE_11_SET_A_W_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 5) if (listBox2.SelectedIndex == 0) { DEGREE_11_SET_A_W_HEAVY.Show(); } else { DEGREE_11_SET_A_W_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 0) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_CLOTHES.Show(); } else { DEGREE_11_SET_B_M_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 1) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_LIGHT.Show(); } else { DEGREE_11_SET_B_M_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 2) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_M_HEAVY.Show(); } else { DEGREE_11_SET_B_M_HEAVY.Visible = false; }
            if (listBox5.SelectedIndex == 3) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_CLOTHES.Show(); } else { DEGREE_11_SET_B_W_CLOTHES.Visible = false; }
            if (listBox5.SelectedIndex == 4) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_LIGHT.Show(); } else { DEGREE_11_SET_B_W_LIGHT.Visible = false; }
            if (listBox5.SelectedIndex == 5) if (listBox2.SelectedIndex == 1) { DEGREE_11_SET_B_W_HEAVY.Show(); } else { DEGREE_11_SET_B_W_HEAVY.Visible = false; }

        }
        private void button1_Click(object sender, EventArgs e)
        {
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_A 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_A 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_A 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_A 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_A 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_A 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_A 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_A 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_A 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_A 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_A 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_A 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_A_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_A_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_A_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_A_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_A_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_A_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_A_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_A_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_A_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_B 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_B 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_B 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_B 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_B 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_B 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_B 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_B 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_B 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_B 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_B 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_B 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_B_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_B_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_CLOTHES_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_CLOTHES_11_AA_SET_B_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_B_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_B_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_LIGHT_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_LIGHT_11_AA_SET_B_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_B_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_B_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_M_HEAVY_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_M_HEAVY_11_AA_SET_B_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_A 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_A 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_A 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_A 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_A 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_A 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_A 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_A 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_A 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_A 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_A 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_A 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_A_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_A_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_A_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_A_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_A_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_A_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_A_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_A_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_A_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_B 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_B 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_B 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_B 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_B 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_B 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_B 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_B 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_B 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_B 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_B 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_B 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_B_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_B_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_CLOTHES_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_CLOTHES_11_AA_SET_B_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_B_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_B_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_LIGHT_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_LIGHT_11_AA_SET_B_RARE 250"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_B_RARE 5"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_B_RARE 15"; }
            if (radioButton2.Checked == true && listBox1.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_CH_W_HEAVY_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_CH_W_HEAVY_11_AA_SET_B_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_A 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_A 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_A 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_A 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_A 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_A 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_A 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_A 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_A 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_A 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_A 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_A 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_A_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_A_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_A_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_A_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_A_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_A_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_A_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_A_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_A_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_B 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_B 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_B 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_B 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_B 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_B 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_B 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_B 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_B 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_B 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_B 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_B 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_B_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_B_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 0 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_CLOTHES_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_CLOTHES_11_AA_SET_B_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_B_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_B_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 1 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_LIGHT_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_LIGHT_11_AA_SET_B_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_B_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_B_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 2 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_M_HEAVY_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_M_HEAVY_11_AA_SET_B_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_A 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_A 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_A 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_A 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_A 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_A 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_A 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_A 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_A 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_A 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_A 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_A 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_A_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_A_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_A_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_A_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_A_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_A_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_A_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_A_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_A_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_A_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 0 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_A_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_A_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_B 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_B 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_B 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_B 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_B 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_B 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_B 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_B 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_B 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_B 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 0 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_B 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_B 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_B_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_B_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 3 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_CLOTHES_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_CLOTHES_11_AA_SET_B_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_B_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_B_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 4 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_LIGHT_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_LIGHT_11_AA_SET_B_RARE 250"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 0) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_B_RARE 5\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_B_RARE 5"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 1) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_B_RARE 15\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_B_RARE 15"; }
            else if (radioButton1.Checked == true && listBox5.SelectedIndex == 5 && listBox2.SelectedIndex == 1 && listBox3.SelectedIndex == 1 && listBox4.SelectedIndex == 2) { textBox1.Text = "/MAKEITEM ITEM_EU_W_HEAVY_11_HA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_SA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_BA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_LA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_FA_SET_B_RARE 250\r\n/MAKEITEM ITEM_EU_W_HEAVY_11_AA_SET_B_RARE 250"; }
        }

        private void LegendaryArmor_Load(object sender, EventArgs e)
        {
            if (Language.Default.language == "English")
            {
                button1.Text = "Show Code";
                button2.Text = "Back";
            }
        }
    }
}
